apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: sample-app-alerts
  namespace: flux-system
  labels:
    release: monitoring
spec:
  groups:
    - name: sample-app.rules
      rules:
        - alert: SampleAppDown
          expr: up{service="sample-app"} == 0
          for: 30s
          labels:
            severity: critical
          annotations:
            summary: "Sample App is down"
            description: "The sample app has not been responding for 30 seconds."
    - name: cpu-alerts
      rules:
        - alert: HighCPUUsage
          expr: sum(rate(container_cpu_usage_seconds_total{pod="cpu-burn", namespace="default"}[2m])) > 0.8
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "High CPU usage detected"
            description: "CPU usage is above 80% for more than 2 minutes."
    - name: memory-alerts
      rules:
        - alert: HighMemoryUsage
          expr: sum(container_memory_working_set_bytes{container!="",pod!=""}) > (0.8 * sum(machine_memory_bytes))
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "High memory usage detected"
            description: "Memory usage is above 80%."
    - name: pod-alerts
      rules:
        - alert: PodCrashLooping
          expr: kube_pod_container_status_restarts_total > 3
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Pod is crash looping"
            description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is restarting frequently."

