apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-values
data:
  values.yaml: |
    grafana:
      adminPassword: "Admin@12345"
      service:
        type: NodePort
        nodePort: 32000

    prometheus:
      service:
        type: NodePort
        nodePort: 32001

    alertmanager:
      service:
        type: NodePort
        nodePort: 32004

