apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app1
  namespace: flux-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-app1
  template:
    metadata:
      labels:
        app: sample-app1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/q/metrics"
    spec:
      containers:
        - name: sample-app1
          image: keeru3108/sample-app1:v1.0
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
