apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-cloud-values
  namespace: flux-system
data:
  values.yaml: |
    cluster:
      name: monitoring-demo

    destinations:
      grafana-cloud-metrics:
        type: prometheus
        url: https://prometheus-prod-65-prod-eu-west-2.grafana.net/api/prom/push
        auth:
          type: basic
          username: "monitoring-demotoken"
          password: "glc_eyJvIjoiTgwOTY4OS..."

    collectors:
      alloy-metrics:
        enabled: true

    clusterMetrics:
      enabled: true
      destinations:
        - grafana-cloud-metrics

    clusterEvents:
      enabled: true
      destinations:
        - grafana-cloud-metrics

    podLogs:
      enabled: false
