apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-values
  namespace: flux-system
data:
  values.yaml: |
    adminPassword: "Admin@12345"

    service:
      type: NodePort
      nodePort: 32000
