apiVersion: v1
kind: ConfigMap
metadata:
  name: opensearch-values
  namespace: flux-system
data:
  values.yaml: |
    clusterName: "opensearch-cluster"
    nodeGroup: "master"

    replicas: 1

    opensearchJavaOpts: "-Xms1g -Xmx1g"

    resources:
      requests:
        memory: "1.5Gi"
      limits:
        memory: "2Gi"

    plugins:
      security:
        disabled: true

    opensearchSecurity:
      enabled: false


    service:
      type: NodePort
      nodePort: 32112
