apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-values
  namespace: flux-system
data:
  values.yaml: |
    prometheus:
      service:
        type: NodePort
        nodePort: 32111

    alertmanager:
      service:
        type: NodePort
        nodePort: 32004

    grafana:
      adminPassword: "Admin123!@"
      service:
        type: NodePort
        nodePort: 32000

      dashboards:
        default:
          node-exporter-full:
            gnetId: 1860
            revision: 27
            datasource: Prometheus
