apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-values
  namespace: flux-system
data:
  values.yaml: |
   

    prometheus:
      service:
        type: NodePort
        nodePort: 32111

    alertmanager:
      service:
        type: NodePort
        nodePort: 32004

