apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Helm repositories
  - manifests/helmrepository/prometheus.yaml
  - manifests/helmrepository/opensearch.yaml

  # Values ConfigMaps
  - values/prometheus-values.yaml
  - values/opensearch-values.yaml
  - values/dashboards-values.yaml

  # Helm releases
  - prometheus-release.yaml
  - opensearch-release.yaml
  - dashboards-release.yaml

  # Sample app
  - manifests/sample-app/deployment.yaml
  - manifests/sample-app/service.yaml
  - manifests/sample-app/servicemonitor.yaml
  - manifests/sample-app/prometheus-rule.yaml

  # Grafana dashboards
  - manifests/grafana/grafana-dashboard-sample.yaml
