apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - prometheus-release.yaml
  - opensearch-release.yaml
  - dashboards-release.yaml
  - ../values/prometheus-values.yaml
  - ../values/opensearch-values.yaml.yaml
  - ../values/dashboards-values.yaml
  - ../values/grafana-values.yaml
